### ISSUE TITLE
Nice People these activities look good!!

### ISSUE THREAD

**Issue by goern** [operate-first/workshop-apps#24]

**Comment by tumido** [comment]
ehm... I wonder what does this @goern guy wants from us.. :smile: :tada:

**Comment by HumairAK** [comment]
Uh can we close this issue now? :)

**Comment by tumido** [comment]
Easy! :racing_car:

![Peek 2021-03-04 18-22](https://user-images.githubusercontent.com/7453394/110003396-9f484c00-7d16-11eb-89f6-7e2195cab81e.gif)
