### ISSUE TITLE
Question: Issue template format for workshops

### ISSUE THREAD

**Issue by pacospace** [operate-first/workshop-apps#4]
@tumido @vpavlin 

What about having a GitHub template issue for a problem in any of the tasks the user has to perform in a workshop, they can cc us and we can review the problem there (virtual event with Github) so we can receive notification and we don’t lose track of anyone.

something like

```
---
name: Workshop issue
about: Task issue during workshop
labels: ws-ml-prague-issue
title: Workshop issue ML Prague
assignees: @vpavlin @pacospace 
---

**Task**
A clear and concise description of the task you have to perform.

**Describe the issue**
A clear and concise description of what problem are you encountering.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

```

We can explain issues live during the workshop.

**Comment by pacospace** [comment]
@tumido @vpavlin cc

**Comment by pacospace** [comment]
Related-to: https://github.com/operate-first/support/issues/77

**Comment by tumido** [comment]
I like that idea! :+1:

**Comment by goern** [comment]
this also enables us to have more people working and helping on the workshop in the background.... +1

**Comment by vpavlin** [comment]
That's great! +1
