### ISSUE TITLE
Workshop issue ML Prague

### ISSUE THREAD

**Issue by oindrillac** [operate-first/workshop-apps#9]
**Task**
Some observations from the Tutorial:

**Typos**
* The demo application used is the "hello world" for AI: MNIST Classication -> Classification.
* This tutorial has been created using Operate First infrustructure and the tools provided in Open Data Hub, which is deployed on Operate First.  -> Infrastructure
* Go to Git Box panel on the left and select Push Changs. -> Changes
* Open issue in Operate First [Support] and equest Prometheus scraping the model endpoint /metrics for the application deployed in your namespace. -> request

**Broken links**
* First `jupyter notebook` url here https://github.com/thoth-station/elyra-aidevsecops-tutorial#manage-dependencies-for-your-new-notebook returns 404
* Open issue in Operate First [Support] and equest Prometheus scraping the model endpoint /metrics for the application deployed in your namespace. - insert url to https://github.com/operate-first/support/issues/new/choose
* Create new Grafana dashbord for the metrics to see how the application and model are performing and open issue in Operate First [Support] on how to have your dashboard deployed. - insert url to https://github.com/operate-first/support/issues/new/choose

**Suggestions for Improvements**
* Consider breaking down the tutorial into 2-3 chapters, since its a detailed and long markdown, splitting the markdown into multiple markdown chapters or modules based on tasks could help streamline attention. 
* In the following section, consider adding the notebook names before the bullet points:
For the purpose of this tutorial you fill find the following notebooks:

1. Download your data with a Python script or Jupyter notebook;

2. Train the model in a Jupyter notebook and store model locally or Ceph;

to

1. `notebook-name.ipynb` - Download your data with a Python script or Jupyter notebook;

2. `notebook-name.ipynb` - Train the model in a Jupyter notebook and store model locally or Ceph;`

* https://github.com/thoth-station/elyra-aidevsecops-tutorial#2-get-access-to-operate-first-and-open-jupyterhub-to-spawn-the-elyra-image -> consider adding a step mentioning that enter the environment variables here, before spawn.
* Are you also expecting participants to run the notebooks manually in this step? https://github.com/thoth-station/elyra-aidevsecops-tutorial#4-start-working-on-your-notebooks - if so, please add a sentence.

**Additional context**
above are some observations while the demo run through during the aicoe ds meetup

cc: @pacospace @vpavlin

**Comment by pacospace** [comment]
@oindrillac Thank you so much!! I will adjust based on your suggestions and solve the issues you encountered!! Thanks a lot 🥇 💯
